const PATH_BASE = "https://api.foursquare.com/v2"
const CLIENT_ID = "client_id=IPS4T3NFEGCXNS42A5VUHCP24B040UCZ1VDVILCPKN1BTWRT"
const CLIENT_SECRET = "client_secret=SZ2R25DJKTDW5VB4HZ5QPENNAQVSBPZWM4I2PHBLXT3ZLMUE"
const V = "v=20180323"
const RADIUS = "radius=5000"
const LIMIT = "limit=3"
const SORT_BY_DISTANCE = "sortByDistance=1"

export { PATH_BASE, CLIENT_ID, CLIENT_SECRET, V, RADIUS, LIMIT, SORT_BY_DISTANCE }